version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8880:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
